linters:
  enable-all: true
  disable:
    - goimports
    - maligned
    - gochecknoglobals
    - gochecknoinits
    - gosec
    - gomnd
    - gomodguard

linters-settings:
  funlen:
    lines: 270
    statements: 130
  gocyclo:
    min-complexity: 100
  gocognit:
    min-complexity: 100
  nestif:
    min-complexity: 50
run:
  timeout: 3m

issues:
  exclude-use-default: true
